# Conda environment for icclim development
name: icclim-devaa
channels:
 - conda-forge
 - defaults
dependencies:
# Core dependencies
 - python>=3.8
 - xclim>=0.33
 - numpy==1.21.5
 - xarray>=0.19
 - dask[array]>=2021.10.0
 - netCDF4>=1.5.7
 - cftime>=1.5.0
 - pyyaml>=6.0
 # Dev dependencies
 - pre-commit
 - pydata-sphinx-theme
 - sphinx
 - black
 - flake8
 - isort
 - pip
 - pylint
 - pytest
 - pytest-cov
 - setuptools
 # Extra dependencies
 - matplotlib
 - cartopy
