# Conda environment for icclim development
name: icclim-dev
channels:
 - conda-forge
 - defaults
dependencies:
# Core dependencies
 - python>=3.8
 - xclim>=0.34
 - numpy==1.21.5
 - xarray>=0.19
 - dask[array]
 - netCDF4>=1.5.7
 - cftime>=1.5.0
 - pyyaml>=6.0
 - rechunker>=0.3.3
 - psutil
 - zarr
 - fsspec
 - dateparser
 # Dev dependencies
 - pre-commit
 - pydata-sphinx-theme
 - sphinx
 - black
 - flake8
 - isort
 - pip
 - pylint
 - pytest
 - pytest-cov
 - setuptools
 - twine
 - flake8-rst-docstrings
 # Extra dependencies
 - matplotlib
 - cartopy
